DROP DATABASE IF EXISTS `HACKATHON`;
CREATE SCHEMA `HACKATHON`;
USE `HACKATHON`;
CREATE TABLE `court_cases` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `court` VARCHAR(50) NOT NULL,
    `date` DATETIME NOT NULL,
    `no` VARCHAR(50) NOT NULL,
    `sys` VARCHAR(50) NOT NULL,
    `reason` VARCHAR(255) NOT NULL,
    `type` VARCHAR(50) NOT NULL,
    `historyHash` VARCHAR(100) NOT NULL,
    `mainText` LONGTEXT NOT NULL,
    `opinion` LONGTEXT NOT NULL,
    `judgement` LONGTEXT NOT NULL,
    `summary` LONGTEXT DEFAULT NULL
);